### ISSUE TITLE
Robot accounts changed in Harbor 2.2.x

### ISSUE THREAD

**Issue by shreddedbacon** [mittwald/goharbor-client#89] opened 2021-04-29 08:18 UTC
There appear to be some changes to robot accounts in Harbor 2.2.x vs 2.1.x

Some fields are renamed, if we look at https://github.com/mittwald/goharbor-client/blob/master/apiv2/model/legacy/robot_account.go#L18-L43

Two things I've noticed so far (there could be more)
* `disabled` is now `disable`
* when creating a robot account with a defined `expires_at` field, Harbor ignores it and creates it with the default 30 days.

Is there a plan to support changes for Harbor 2.2.x ?

**Comment by elenz97** [comment] 2021-06-30 09:37
Duplicate of https://github.com/mittwald/goharbor-client/issues/85

**Closed by elenz97** 2021-06-30 09:37 UTC
Labels: api/v2, duplicate
